[[constraint]]
  version = "^2.1.0"
  name = "periph.io/x/periph"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "^0.8.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
