[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "^1.0.3"

[[constraint]]
  version = "^2.1.0"
  name = "periph.io/x/periph"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true